name: "[www] Deploy production"

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup production deployment ⚙️
    uses: ./.github/workflows/vercel-setup.yaml
    secrets: inherit
    with:
      environment: production

  deploy:
    name: Build production deployment 🚀
    needs: setup
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Application
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Application
        run: vercel deploy --prebuilt --prod --skip-domain --token=${{ secrets.VERCEL_TOKEN }}
