name: "[workflow] Deploy to Vercel"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: string

jobs:
  deploy:
    name: "Setup deployment for '${{inputs.environment}}' environment"
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
